name: self_care
description: SEN3006 Software Arch. Lab Project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  http: ^0.12.0+2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.4.0
  health: ^3.0.5
  youtube_player_flutter: ^8.0.0
  fl_chart: ^0.36.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


